import Head from 'next/head';
import Script from 'next/script';
import Approach from '../components/Approach';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Objectives from '../components/Objectives';
import Projects from '../components/Projects';
import Services from '../components/Services';
import Technoligies from '../components/Technoligies';


export default function Home() {
  return (
    <div className='sm:flex sm:flex-col sm:justify-start overflow-hidden'>
      <Head>
        <title>cubicus.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        strategy="lazyOnload"
        src="https://embed.tawk.to/644104a731ebfa0fe7f9688a/1guevkcgg"
      />
      <Hero />
      {/* <MyHero /> */}
      <Services />
      <Projects />
      <Approach />
      <Technoligies />
      <Objectives />
      {/* <Reviews /> */}
      {/* <Pricing /> */}
      <Contact />
      <Footer />
      {/* <Slider slides={SliderData} /> */}

    </div>

  );
}
